from .schemas import MarketOverviewResponse, StockSentimentResponse


MOCK_STOCK_SENTIMENT: dict[str, StockSentimentResponse] = {
    "BHP": StockSentimentResponse(
        ticker="BHP",
        company_name="BHP Group Ltd",
        market="ASX",
        sector="Materials",
        industry="Metals & Mining",
        description="BHP Group Ltd is a diversified resources company with operations spanning iron ore, copper, coal, and potash.",
        exchange="ASX",
        currency="AUD",
        market_cap="220B",
        latest_price=46.28,
        day_change_percent=1.8,
        volume=15420000,
        overall_sentiment="Positive",
        confidence=0.84,
        summary=(
            "Recent coverage suggests improving investor confidence in BHP, supported by stable "
            "production commentary, resilient commodity demand expectations, and disciplined "
            "capital allocation."
        ),
        article_count=4,
        news_items=[
            {
                "title": "BHP shares lift after quarterly production update meets expectations",
                "source": "Reuters",
                "published_at": "2026-04-13T01:30:00Z",
                "sentiment": "Positive",
                "snippet": "Investors reacted positively after BHP reported steady output across key operations.",
                "url": "https://example.com/bhp-production-update",
            },
            {
                "title": "Analysts highlight resilient iron ore demand in BHP outlook",
                "source": "Australian Financial Review",
                "published_at": "2026-04-12T23:20:00Z",
                "sentiment": "Positive",
                "snippet": "Broker commentary pointed to supportive commodity demand and stable earnings expectations.",
                "url": "https://example.com/bhp-demand-outlook",
            },
            {
                "title": "Miners trade mixed as investors assess China-linked demand signals",
                "source": "The Australian",
                "published_at": "2026-04-12T20:05:00Z",
                "sentiment": "Neutral",
                "snippet": "Sector coverage noted BHP remained resilient despite uneven performance across resources.",
                "url": "https://example.com/bhp-sector-wrap",
            },
            {
                "title": "BHP seen maintaining balance sheet flexibility amid growth plans",
                "source": "MarketWatch",
                "published_at": "2026-04-12T12:10:00Z",
                "sentiment": "Positive",
                "snippet": "Commentary emphasized spending discipline and continued financial flexibility.",
                "url": "https://example.com/bhp-balance-sheet",
            },
        ],
    ),
    "CBA": StockSentimentResponse(
        ticker="CBA",
        company_name="Commonwealth Bank of Australia",
        market="ASX",
        sector="Financials",
        industry="Diversified Banks",
        description="Commonwealth Bank of Australia is one of the largest financial institutions in Australia, serving retail, business, and institutional customers.",
        exchange="ASX",
        currency="AUD",
        market_cap="198B",
        latest_price=118.42,
        day_change_percent=0.2,
        volume=6450000,
        overall_sentiment="Neutral",
        confidence=0.76,
        summary=(
            "News sentiment for CBA is balanced. Investors remain constructive on franchise "
            "strength, but premium valuation and margin pressure keep the tone mixed."
        ),
        article_count=3,
        news_items=[
            {
                "title": "CBA holds firm as investors assess resilience across major banks",
                "source": "Reuters",
                "published_at": "2026-04-13T00:10:00Z",
                "sentiment": "Neutral",
                "snippet": "Analysts described CBA as operationally solid but noted valuation remains demanding.",
                "url": "https://example.com/cba-resilience",
            },
            {
                "title": "Deposit competition may pressure bank margins, broker says",
                "source": "The Sydney Morning Herald",
                "published_at": "2026-04-12T22:00:00Z",
                "sentiment": "Negative",
                "snippet": "Coverage focused on tighter funding competition and slower margin expansion.",
                "url": "https://example.com/cba-margins",
            },
            {
                "title": "CBA digital investment supports long-term growth narrative",
                "source": "The Australian Financial Review",
                "published_at": "2026-04-12T18:40:00Z",
                "sentiment": "Positive",
                "snippet": "Recent reporting highlighted continued customer engagement improvement from digital channels.",
                "url": "https://example.com/cba-digital-growth",
            },
        ],
    ),
    "CSL": StockSentimentResponse(
        ticker="CSL",
        company_name="CSL Limited",
        market="ASX",
        sector="Health Care",
        industry="Biotechnology",
        description="CSL Limited develops and delivers biotherapies, vaccines, and plasma-derived medicines across global healthcare markets.",
        exchange="ASX",
        currency="AUD",
        market_cap="146B",
        latest_price=301.15,
        day_change_percent=1.4,
        volume=1210000,
        overall_sentiment="Positive",
        confidence=0.81,
        summary=(
            "CSL sentiment remains positive as recent coverage highlights improving plasma "
            "collection trends, margin recovery expectations, and durable demand across therapies."
        ),
        article_count=3,
        news_items=[
            {
                "title": "CSL advances after analysts cite improving plasma collection trends",
                "source": "Reuters",
                "published_at": "2026-04-13T02:05:00Z",
                "sentiment": "Positive",
                "snippet": "Market commentary pointed to better donor center productivity and margin normalization potential.",
                "url": "https://example.com/csl-plasma-trends",
            },
            {
                "title": "Healthcare note highlights defensive appeal of CSL earnings profile",
                "source": "Morningstar",
                "published_at": "2026-04-12T23:50:00Z",
                "sentiment": "Positive",
                "snippet": "Analysts said CSL continues to offer relatively strong earnings visibility.",
                "url": "https://example.com/csl-defensive",
            },
            {
                "title": "FX headwinds remain part of CSL investment debate",
                "source": "The Australian",
                "published_at": "2026-04-12T17:25:00Z",
                "sentiment": "Neutral",
                "snippet": "Operational trends are improving, though currency moves remain a watchpoint.",
                "url": "https://example.com/csl-fx",
            },
        ],
    ),
    "WES": StockSentimentResponse(
        ticker="WES",
        company_name="Wesfarmers Limited",
        market="ASX",
        sector="Consumer",
        industry="Retail Conglomerates",
        description="Wesfarmers Limited is a diversified Australian group with businesses in retail, chemicals, and industrial operations.",
        exchange="ASX",
        currency="AUD",
        market_cap="79B",
        latest_price=69.87,
        day_change_percent=1.1,
        volume=2860000,
        overall_sentiment="Positive",
        confidence=0.79,
        summary=(
            "Recent Wesfarmers coverage is moderately positive, reflecting confidence in retail "
            "execution, resilient demand pockets, and continued portfolio discipline."
        ),
        article_count=3,
        news_items=[
            {
                "title": "Wesfarmers edges higher as Bunnings update supports stability view",
                "source": "Reuters",
                "published_at": "2026-04-13T01:05:00Z",
                "sentiment": "Positive",
                "snippet": "Investors welcomed signs of steady trading conditions and ongoing home improvement demand.",
                "url": "https://example.com/wes-bunnings",
            },
            {
                "title": "Analysts see selective consumer strength supporting Wesfarmers",
                "source": "Australian Financial Review",
                "published_at": "2026-04-12T21:15:00Z",
                "sentiment": "Positive",
                "snippet": "Coverage suggested diversified retail exposure is cushioning weaker discretionary segments.",
                "url": "https://example.com/wes-consumer",
            },
            {
                "title": "Cost inflation remains a watchpoint for diversified retailers",
                "source": "The Sydney Morning Herald",
                "published_at": "2026-04-12T16:55:00Z",
                "sentiment": "Neutral",
                "snippet": "Reporting noted margin discipline remains important even as sales trends stay constructive.",
                "url": "https://example.com/wes-inflation",
            },
        ],
    ),
}


MOCK_MARKET_OVERVIEW = MarketOverviewResponse(
    market="ASX",
    overall_sentiment="Positive",
    summary=(
        "ASX market tone is mildly constructive today, led by materials and healthcare, while "
        "banks remain more mixed on valuation and margin expectations."
    ),
    updated_at="2026-04-13T03:00:00Z",
    advancing_blocks=5,
    declining_blocks=2,
    neutral_blocks=1,
    heatmap=[
        {
            "ticker": "BHP",
            "company_name": "BHP Group Ltd",
            "sector": "Materials",
            "sentiment": "Positive",
            "weight": 18,
            "change_percent": 1.8,
            "summary": "Production stability and firmer commodity sentiment supported miners.",
        },
        {
            "ticker": "CBA",
            "company_name": "Commonwealth Bank of Australia",
            "sector": "Financials",
            "sentiment": "Neutral",
            "weight": 16,
            "change_percent": 0.2,
            "summary": "Banks were steady as investors balanced resilience against valuation concerns.",
        },
        {
            "ticker": "CSL",
            "company_name": "CSL Limited",
            "sector": "Health Care",
            "sentiment": "Positive",
            "weight": 14,
            "change_percent": 1.4,
            "summary": "Healthcare sentiment improved on margin recovery expectations.",
        },
        {
            "ticker": "WES",
            "company_name": "Wesfarmers Limited",
            "sector": "Consumer",
            "sentiment": "Positive",
            "weight": 10,
            "change_percent": 1.1,
            "summary": "Retail execution and resilient demand pockets helped consumer names.",
        },
        {
            "ticker": "NAB",
            "company_name": "National Australia Bank",
            "sector": "Financials",
            "sentiment": "Negative",
            "weight": 9,
            "change_percent": -0.9,
            "summary": "Margin pressure concerns kept sentiment softer across parts of the banking sector.",
        },
        {
            "ticker": "FMG",
            "company_name": "Fortescue Ltd",
            "sector": "Materials",
            "sentiment": "Positive",
            "weight": 8,
            "change_percent": 2.3,
            "summary": "Stronger iron ore narrative pushed sentiment higher for bulk commodity names.",
        },
        {
            "ticker": "MQG",
            "company_name": "Macquarie Group Ltd",
            "sector": "Financials",
            "sentiment": "Neutral",
            "weight": 7,
            "change_percent": 0.1,
            "summary": "Investor stance stayed balanced while awaiting clearer earnings catalysts.",
        },
        {
            "ticker": "WOW",
            "company_name": "Woolworths Group Ltd",
            "sector": "Consumer",
            "sentiment": "Negative",
            "weight": 7,
            "change_percent": -0.6,
            "summary": "Competitive pressure kept grocery sentiment a little more cautious.",
        },
    ],
)
