ASX_TICKER_SEARCH = {
    "BHP": {
        "company_name": "BHP Group Ltd",
        "alpha_symbol": "BHP.AX",
        "twelve_symbol": "BHP:XASX",
        "search_query": '("BHP Group" OR "BHP Group Ltd" OR "BHP shares" OR "ASX:BHP")',
        "search_queries": [
            '("BHP Group" OR "BHP Group Ltd" OR "BHP shares" OR "ASX:BHP")',
            '("BHP" AND (miner OR mining OR ASX OR shares OR iron ore))',
        ],
        "sector": "Materials",
        "weight": 18,
        "keywords": ["bhp", "bhp group", "asx:bhp", "bhp shares"],
    },
    "CBA": {
        "company_name": "Commonwealth Bank of Australia",
        "alpha_symbol": "CBA.AX",
        "twelve_symbol": "CBA:XASX",
        "search_query": '("Commonwealth Bank of Australia" OR "CommBank" OR "ASX:CBA" OR "CBA shares")',
        "search_queries": [
            '("Commonwealth Bank of Australia" OR "CommBank" OR "ASX:CBA" OR "CBA shares")',
            '("CBA" AND (bank OR banking OR ASX OR shares))',
        ],
        "sector": "Financials",
        "weight": 16,
        "keywords": ["commonwealth bank", "commbank", "asx:cba", "cba shares"],
    },
    "CSL": {
        "company_name": "CSL Limited",
        "alpha_symbol": "CSL.AX",
        "twelve_symbol": "CSL:XASX",
        "search_query": '("CSL Limited" OR "ASX:CSL" OR "CSL shares")',
        "search_queries": [
            '("CSL Limited" OR "ASX:CSL" OR "CSL shares")',
            '("CSL" AND (biotech OR plasma OR ASX OR shares))',
        ],
        "sector": "Health Care",
        "weight": 14,
        "keywords": ["csl limited", "asx:csl", "csl shares"],
    },
    "WES": {
        "company_name": "Wesfarmers Limited",
        "alpha_symbol": "WES.AX",
        "twelve_symbol": "WES:XASX",
        "search_query": '("Wesfarmers Limited" OR Wesfarmers OR "ASX:WES" OR "WES shares")',
        "search_queries": [
            '("Wesfarmers Limited" OR Wesfarmers OR "ASX:WES" OR "WES shares")',
            '("WES" AND (Wesfarmers OR ASX OR shares))',
        ],
        "sector": "Consumer",
        "weight": 10,
        "keywords": ["wesfarmers", "asx:wes", "wes shares"],
    },
    "NAB": {
        "company_name": "National Australia Bank",
        "alpha_symbol": "NAB.AX",
        "twelve_symbol": "NAB:XASX",
        "search_query": '("National Australia Bank" OR "NAB shares" OR "ASX:NAB")',
        "search_queries": [
            '("National Australia Bank" OR "NAB shares" OR "ASX:NAB")',
            '("NAB" AND (bank OR banking OR ASX OR shares))',
        ],
        "sector": "Financials",
        "weight": 9,
        "keywords": ["national australia bank", "nab shares", "asx:nab"],
    },
    "FMG": {
        "company_name": "Fortescue Ltd",
        "alpha_symbol": "FMG.AX",
        "twelve_symbol": "FMG:XASX",
        "search_query": '("Fortescue" OR "Fortescue Ltd" OR "ASX:FMG" OR "FMG shares")',
        "search_queries": [
            '("Fortescue" OR "Fortescue Ltd" OR "ASX:FMG" OR "FMG shares")',
            '("FMG" AND (Fortescue OR ASX OR shares OR iron ore))',
        ],
        "sector": "Materials",
        "weight": 8,
        "keywords": ["fortescue", "fortescue ltd", "asx:fmg", "fmg shares"],
    },
    "MQG": {
        "company_name": "Macquarie Group Ltd",
        "alpha_symbol": "MQG.AX",
        "twelve_symbol": "MQG:XASX",
        "search_query": '("Macquarie Group" OR Macquarie OR "ASX:MQG" OR "MQG shares")',
        "search_queries": [
            '("Macquarie Group" OR Macquarie OR "ASX:MQG" OR "MQG shares")',
            '("MQG" AND (Macquarie OR ASX OR shares))',
        ],
        "sector": "Financials",
        "weight": 7,
        "keywords": ["macquarie group", "macquarie", "asx:mqg", "mqg shares"],
    },
    "WOW": {
        "company_name": "Woolworths Group Ltd",
        "alpha_symbol": "WOW.AX",
        "twelve_symbol": "WOW:XASX",
        "search_query": '("Woolworths Group" OR Woolworths OR "ASX:WOW" OR "WOW shares")',
        "search_queries": [
            '("Woolworths Group" OR Woolworths OR "ASX:WOW" OR "WOW shares")',
            '("WOW" AND (Woolworths OR ASX OR shares OR retail))',
        ],
        "sector": "Consumer",
        "weight": 7,
        "keywords": ["woolworths group", "woolworths", "asx:wow", "wow shares"],
    },
}
